// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"

	repo "github.com/CodeWithKrushnal/ChainBank/internal/repo"

	user "github.com/CodeWithKrushnal/ChainBank/internal/app/user"

	utils "github.com/CodeWithKrushnal/ChainBank/utils"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AuthenticateUser provides a mock function with given fields: ctx, credentials, originIP
func (_m *Service) AuthenticateUser(ctx context.Context, credentials utils.Credentials, originIP string) (map[string]string, error) {
	ret := _m.Called(ctx, credentials, originIP)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, utils.Credentials, string) (map[string]string, error)); ok {
		return rf(ctx, credentials, originIP)
	}
	if rf, ok := ret.Get(0).(func(context.Context, utils.Credentials, string) map[string]string); ok {
		r0 = rf(ctx, credentials, originIP)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, utils.Credentials, string) error); ok {
		r1 = rf(ctx, credentials, originIP)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUserAccount provides a mock function with given fields: ctx, req
func (_m *Service) CreateUserAccount(ctx context.Context, req user.SignupRequest) (repo.User, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserAccount")
	}

	var r0 repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.SignupRequest) (repo.User, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.SignupRequest) repo.User); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.SignupRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExecuteQuery provides a mock function with given fields: ctx, query, args
func (_m *Service) ExecuteQuery(ctx context.Context, query string, args ...interface{}) (interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteQuery")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (interface{}, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) interface{}); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateAndSendResetToken provides a mock function with given fields: ctx, email
func (_m *Service) GenerateAndSendResetToken(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAndSendResetToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateEmailVerificationToken provides a mock function with given fields: ctx, email, originIP
func (_m *Service) GenerateEmailVerificationToken(ctx context.Context, email string, originIP string) (string, error) {
	ret := _m.Called(ctx, email, originIP)

	if len(ret) == 0 {
		panic("no return value specified for GenerateEmailVerificationToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, originIP)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, originIP)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, originIP)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllKYCVerificationsService provides a mock function with given fields: ctx
func (_m *Service) GetAllKYCVerificationsService(ctx context.Context) ([]repo.KYCRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKYCVerificationsService")
	}

	var r0 []repo.KYCRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]repo.KYCRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []repo.KYCRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.KYCRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfig provides a mock function with given fields: ctx
func (_m *Service) GetConfig(ctx context.Context) (utils.ConfigStruct, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 utils.ConfigStruct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (utils.ConfigStruct, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) utils.ConfigStruct); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(utils.ConfigStruct)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKYCDetailedInfo provides a mock function with given fields: ctx, kycID, userEmail
func (_m *Service) GetKYCDetailedInfo(ctx context.Context, kycID string, userEmail string) ([]repo.KYCRecord, error) {
	ret := _m.Called(ctx, kycID, userEmail)

	if len(ret) == 0 {
		panic("no return value specified for GetKYCDetailedInfo")
	}

	var r0 []repo.KYCRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]repo.KYCRecord, error)); ok {
		return rf(ctx, kycID, userEmail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []repo.KYCRecord); ok {
		r0 = rf(ctx, kycID, userEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.KYCRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, kycID, userEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRequestLogStats provides a mock function with given fields: ctx, filter
func (_m *Service) GetRequestLogStats(ctx context.Context, filter repo.RequestLogStatsFilter) (interface{}, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestLogStats")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.RequestLogStatsFilter) (interface{}, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.RequestLogStatsFilter) interface{}); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.RequestLogStatsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRequestLogs provides a mock function with given fields: ctx, filter
func (_m *Service) GetRequestLogs(ctx context.Context, filter repo.RequestLogFilter) ([]repo.RequestLog, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestLogs")
	}

	var r0 []repo.RequestLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.RequestLogFilter) ([]repo.RequestLog, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.RequestLogFilter) []repo.RequestLog); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.RequestLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.RequestLogFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionStats provides a mock function with given fields: ctx, filter
func (_m *Service) GetTransactionStats(ctx context.Context, filter repo.TransactionStatsFilter) (interface{}, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionStats")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.TransactionStatsFilter) (interface{}, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.TransactionStatsFilter) interface{}); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.TransactionStatsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *Service) GetUserByEmail(ctx context.Context, email string) (repo.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repo.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repo.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *Service) GetUserByID(ctx context.Context, userID string) (utils.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 utils.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (utils.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) utils.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(utils.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserInfo provides a mock function with given fields: ctx, userID
func (_m *Service) GetUserInfo(ctx context.Context, userID string) (utils.UserInfo, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 utils.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (utils.UserInfo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) utils.UserInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(utils.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertKYCVerificationService provides a mock function with given fields: ctx, UserEmail, documentType, documentNumber, verificationStatus
func (_m *Service) InsertKYCVerificationService(ctx context.Context, UserEmail string, documentType string, documentNumber string, verificationStatus string) (string, error) {
	ret := _m.Called(ctx, UserEmail, documentType, documentNumber, verificationStatus)

	if len(ret) == 0 {
		panic("no return value specified for InsertKYCVerificationService")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (string, error)); ok {
		return rf(ctx, UserEmail, documentType, documentNumber, verificationStatus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) string); ok {
		r0 = rf(ctx, UserEmail, documentType, documentNumber, verificationStatus)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, UserEmail, documentType, documentNumber, verificationStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendEmail provides a mock function with given fields: ctx, email, subject, message
func (_m *Service) SendEmail(ctx context.Context, email string, subject string, message string) error {
	ret := _m.Called(ctx, email, subject, message)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, email, subject, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateKYCVerificationStatusService provides a mock function with given fields: ctx, kycID, verificationStatus, verifiedBy
func (_m *Service) UpdateKYCVerificationStatusService(ctx context.Context, kycID string, verificationStatus string, verifiedBy string) error {
	ret := _m.Called(ctx, kycID, verificationStatus, verifiedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKYCVerificationStatusService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, kycID, verificationStatus, verifiedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateAndResetPassword provides a mock function with given fields: ctx, resetToken, newPassword
func (_m *Service) ValidateAndResetPassword(ctx context.Context, resetToken string, newPassword string) error {
	ret := _m.Called(ctx, resetToken, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAndResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, resetToken, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateEmailVerificationToken provides a mock function with given fields: tokenString
func (_m *Service) ValidateEmailVerificationToken(tokenString string) (jwt.MapClaims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEmailVerificationToken")
	}

	var r0 jwt.MapClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (jwt.MapClaims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) jwt.MapClaims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateResetToken provides a mock function with given fields: tokenString
func (_m *Service) ValidateResetToken(tokenString string) (jwt.MapClaims, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateResetToken")
	}

	var r0 jwt.MapClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (jwt.MapClaims, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) jwt.MapClaims); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.MapClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
