// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	loan "github.com/CodeWithKrushnal/ChainBank/internal/app/loan"
	mock "github.com/stretchr/testify/mock"

	repo "github.com/CodeWithKrushnal/ChainBank/internal/repo"

	utils "github.com/CodeWithKrushnal/ChainBank/utils"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AcceptOffer provides a mock function with given fields: ctx, offerID, borrowerID
func (_m *Service) AcceptOffer(ctx context.Context, offerID string, borrowerID string) (repo.LoanOffer, error) {
	ret := _m.Called(ctx, offerID, borrowerID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptOffer")
	}

	var r0 repo.LoanOffer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (repo.LoanOffer, error)); ok {
		return rf(ctx, offerID, borrowerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) repo.LoanOffer); ok {
		r0 = rf(ctx, offerID, borrowerID)
	} else {
		r0 = ret.Get(0).(repo.LoanOffer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, offerID, borrowerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculateTotalPayable provides a mock function with given fields: ctx, loanID, userID
func (_m *Service) CalculateTotalPayable(ctx context.Context, loanID string, userID string) (loan.PayableBreakdown, error) {
	ret := _m.Called(ctx, loanID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CalculateTotalPayable")
	}

	var r0 loan.PayableBreakdown
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (loan.PayableBreakdown, error)); ok {
		return rf(ctx, loanID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) loan.PayableBreakdown); ok {
		r0 = rf(ctx, loanID, userID)
	} else {
		r0 = ret.Get(0).(loan.PayableBreakdown)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, loanID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLoanOffer provides a mock function with given fields: ctx, lenderID, amount, interestRate, termMonths, applicationID
func (_m *Service) CreateLoanOffer(ctx context.Context, lenderID string, amount float64, interestRate float64, termMonths int, applicationID string) (repo.LoanOffer, error) {
	ret := _m.Called(ctx, lenderID, amount, interestRate, termMonths, applicationID)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoanOffer")
	}

	var r0 repo.LoanOffer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, float64, int, string) (repo.LoanOffer, error)); ok {
		return rf(ctx, lenderID, amount, interestRate, termMonths, applicationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, float64, int, string) repo.LoanOffer); ok {
		r0 = rf(ctx, lenderID, amount, interestRate, termMonths, applicationID)
	} else {
		r0 = ret.Get(0).(repo.LoanOffer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64, float64, int, string) error); ok {
		r1 = rf(ctx, lenderID, amount, interestRate, termMonths, applicationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateLoanapplication provides a mock function with given fields: ctx, borrowerID, amount, interestRate, termMonths
func (_m *Service) CreateLoanapplication(ctx context.Context, borrowerID string, amount float64, interestRate float64, termMonths int) (repo.Loanapplication, error) {
	ret := _m.Called(ctx, borrowerID, amount, interestRate, termMonths)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoanapplication")
	}

	var r0 repo.Loanapplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, float64, int) (repo.Loanapplication, error)); ok {
		return rf(ctx, borrowerID, amount, interestRate, termMonths)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, float64, int) repo.Loanapplication); ok {
		r0 = rf(ctx, borrowerID, amount, interestRate, termMonths)
	} else {
		r0 = ret.Get(0).(repo.Loanapplication)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64, float64, int) error); ok {
		r1 = rf(ctx, borrowerID, amount, interestRate, termMonths)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisburseLoan provides a mock function with given fields: ctx, lenderID, offerID
func (_m *Service) DisburseLoan(ctx context.Context, lenderID string, offerID string) (repo.Loan, error) {
	ret := _m.Called(ctx, lenderID, offerID)

	if len(ret) == 0 {
		panic("no return value specified for DisburseLoan")
	}

	var r0 repo.Loan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (repo.Loan, error)); ok {
		return rf(ctx, lenderID, offerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) repo.Loan); ok {
		r0 = rf(ctx, lenderID, offerID)
	} else {
		r0 = ret.Get(0).(repo.Loan)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, lenderID, offerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoanDetails provides a mock function with given fields: ctx, loanID, offerID, borrowerID, lenderID, status, applicationID
func (_m *Service) GetLoanDetails(ctx context.Context, loanID string, offerID string, borrowerID string, lenderID string, status string, applicationID string) ([]repo.Loan, error) {
	ret := _m.Called(ctx, loanID, offerID, borrowerID, lenderID, status, applicationID)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanDetails")
	}

	var r0 []repo.Loan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) ([]repo.Loan, error)); ok {
		return rf(ctx, loanID, offerID, borrowerID, lenderID, status, applicationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) []repo.Loan); ok {
		r0 = rf(ctx, loanID, offerID, borrowerID, lenderID, status, applicationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Loan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, loanID, offerID, borrowerID, lenderID, status, applicationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoanOffers provides a mock function with given fields: ctx, offerID, applicationID, lenderID, status
func (_m *Service) GetLoanOffers(ctx context.Context, offerID string, applicationID string, lenderID string, status string) ([]repo.LoanOffer, error) {
	ret := _m.Called(ctx, offerID, applicationID, lenderID, status)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanOffers")
	}

	var r0 []repo.LoanOffer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]repo.LoanOffer, error)); ok {
		return rf(ctx, offerID, applicationID, lenderID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) []repo.LoanOffer); ok {
		r0 = rf(ctx, offerID, applicationID, lenderID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.LoanOffer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, offerID, applicationID, lenderID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLoanapplications provides a mock function with given fields: ctx, applicationID, borrowerID, status
func (_m *Service) GetLoanapplications(ctx context.Context, applicationID string, borrowerID string, status string) ([]repo.Loanapplication, error) {
	ret := _m.Called(ctx, applicationID, borrowerID, status)

	if len(ret) == 0 {
		panic("no return value specified for GetLoanapplications")
	}

	var r0 []repo.Loanapplication
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]repo.Loanapplication, error)); ok {
		return rf(ctx, applicationID, borrowerID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []repo.Loanapplication); ok {
		r0 = rf(ctx, applicationID, borrowerID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Loanapplication)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, applicationID, borrowerID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *Service) GetUserByID(ctx context.Context, userID string) (utils.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 utils.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (utils.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) utils.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(utils.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettleLoan provides a mock function with given fields: ctx, userID, loanID
func (_m *Service) SettleLoan(ctx context.Context, userID string, loanID string) (repo.Loan, error) {
	ret := _m.Called(ctx, userID, loanID)

	if len(ret) == 0 {
		panic("no return value specified for SettleLoan")
	}

	var r0 repo.Loan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (repo.Loan, error)); ok {
		return rf(ctx, userID, loanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) repo.Loan); ok {
		r0 = rf(ctx, userID, loanID)
	} else {
		r0 = ret.Get(0).(repo.Loan)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, loanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
