// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	ecdsa "crypto/ecdsa"

	mock "github.com/stretchr/testify/mock"

	repo "github.com/CodeWithKrushnal/ChainBank/internal/repo"

	utils "github.com/CodeWithKrushnal/ChainBank/utils"

	wallet "github.com/CodeWithKrushnal/ChainBank/internal/app/wallet"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddTransaction provides a mock function with given fields: ctx, data
func (_m *Service) AddTransaction(ctx context.Context, data wallet.TransactionData) (repo.Transaction, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AddTransaction")
	}

	var r0 repo.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, wallet.TransactionData) (repo.Transaction, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, wallet.TransactionData) repo.Transaction); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(repo.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, wallet.TransactionData) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchTransactions provides a mock function with given fields: ctx, filter
func (_m *Service) FetchTransactions(ctx context.Context, filter wallet.TransactionFilter) ([]repo.Transaction, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FetchTransactions")
	}

	var r0 []repo.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, wallet.TransactionFilter) ([]repo.Transaction, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, wallet.TransactionFilter) []repo.Transaction); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, wallet.TransactionFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBalanceByWalletID provides a mock function with given fields: ctx, walletID
func (_m *Service) GetBalanceByWalletID(ctx context.Context, walletID string) (*big.Float, error) {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalanceByWalletID")
	}

	var r0 *big.Float
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*big.Float, error)); ok {
		return rf(ctx, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *big.Float); ok {
		r0 = rf(ctx, walletID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Float)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *Service) GetUserByID(ctx context.Context, userID string) (utils.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 utils.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (utils.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) utils.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(utils.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletIDForUser provides a mock function with given fields: ctx, userInfo, queryEmail, queryUserID
func (_m *Service) GetWalletIDForUser(ctx context.Context, userInfo utils.User, queryEmail string, queryUserID string) (string, error) {
	ret := _m.Called(ctx, userInfo, queryEmail, queryUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletIDForUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, utils.User, string, string) (string, error)); ok {
		return rf(ctx, userInfo, queryEmail, queryUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, utils.User, string, string) string); ok {
		r0 = rf(ctx, userInfo, queryEmail, queryUserID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, utils.User, string, string) error); ok {
		r1 = rf(ctx, userInfo, queryEmail, queryUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferFunds provides a mock function with given fields: ctx, userInfo, req
func (_m *Service) TransferFunds(ctx context.Context, userInfo utils.User, req wallet.TransferRequest) (repo.Transaction, *big.Int, error) {
	ret := _m.Called(ctx, userInfo, req)

	if len(ret) == 0 {
		panic("no return value specified for TransferFunds")
	}

	var r0 repo.Transaction
	var r1 *big.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, utils.User, wallet.TransferRequest) (repo.Transaction, *big.Int, error)); ok {
		return rf(ctx, userInfo, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, utils.User, wallet.TransferRequest) repo.Transaction); ok {
		r0 = rf(ctx, userInfo, req)
	} else {
		r0 = ret.Get(0).(repo.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, utils.User, wallet.TransferRequest) *big.Int); ok {
		r1 = rf(ctx, userInfo, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*big.Int)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, utils.User, wallet.TransferRequest) error); ok {
		r2 = rf(ctx, userInfo, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ValidateSenderAddress provides a mock function with given fields: ctx, senderWalletID, privateKey
func (_m *Service) ValidateSenderAddress(ctx context.Context, senderWalletID string, privateKey *ecdsa.PrivateKey) error {
	ret := _m.Called(ctx, senderWalletID, privateKey)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSenderAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *ecdsa.PrivateKey) error); ok {
		r0 = rf(ctx, senderWalletID, privateKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateUserPassword provides a mock function with given fields: ctx, email, password
func (_m *Service) ValidateUserPassword(ctx context.Context, email string, password string) error {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
