// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	repo "github.com/CodeWithKrushnal/ChainBank/internal/repo"
	mock "github.com/stretchr/testify/mock"

	utils "github.com/CodeWithKrushnal/ChainBank/utils"
)

// UserStorer is an autogenerated mock type for the UserStorer type
type UserStorer struct {
	mock.Mock
}

// CreateRequestLog provides a mock function with given fields: ctx, requestID, userID, endpoint, httpMethod, requestPayload, ipAddress
func (_m *UserStorer) CreateRequestLog(ctx context.Context, requestID string, userID string, endpoint string, httpMethod string, requestPayload interface{}, ipAddress string) (string, error) {
	ret := _m.Called(ctx, requestID, userID, endpoint, httpMethod, requestPayload, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequestLog")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, interface{}, string) (string, error)); ok {
		return rf(ctx, requestID, userID, endpoint, httpMethod, requestPayload, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, interface{}, string) string); ok {
		r0 = rf(ctx, requestID, userID, endpoint, httpMethod, requestPayload, ipAddress)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, interface{}, string) error); ok {
		r1 = rf(ctx, requestID, userID, endpoint, httpMethod, requestPayload, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, params
func (_m *UserStorer) CreateUser(ctx context.Context, params repo.CreateUserParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.CreateUserParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecuteQuery provides a mock function with given fields: ctx, query, args
func (_m *UserStorer) ExecuteQuery(ctx context.Context, query string, args ...interface{}) (interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteQuery")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (interface{}, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) interface{}); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllKYCVerifications provides a mock function with given fields: ctx
func (_m *UserStorer) GetAllKYCVerifications(ctx context.Context) ([]repo.KYCRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKYCVerifications")
	}

	var r0 []repo.KYCRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]repo.KYCRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []repo.KYCRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.KYCRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKYCDetailedInfo provides a mock function with given fields: ctx, kycID, userID
func (_m *UserStorer) GetKYCDetailedInfo(ctx context.Context, kycID string, userID string) ([]repo.KYCRecord, error) {
	ret := _m.Called(ctx, kycID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetKYCDetailedInfo")
	}

	var r0 []repo.KYCRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]repo.KYCRecord, error)); ok {
		return rf(ctx, kycID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []repo.KYCRecord); ok {
		r0 = rf(ctx, kycID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.KYCRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, kycID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRequestLogStats provides a mock function with given fields: ctx, filter
func (_m *UserStorer) GetRequestLogStats(ctx context.Context, filter repo.RequestLogStatsFilter) (interface{}, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestLogStats")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.RequestLogStatsFilter) (interface{}, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.RequestLogStatsFilter) interface{}); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.RequestLogStatsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRequestLogs provides a mock function with given fields: ctx, filter
func (_m *UserStorer) GetRequestLogs(ctx context.Context, filter repo.RequestLogFilter) ([]repo.RequestLog, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestLogs")
	}

	var r0 []repo.RequestLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.RequestLogFilter) ([]repo.RequestLog, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.RequestLogFilter) []repo.RequestLog); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.RequestLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.RequestLogFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionStats provides a mock function with given fields: ctx, filter
func (_m *UserStorer) GetTransactionStats(ctx context.Context, filter repo.TransactionStatsFilter) (interface{}, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionStats")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repo.TransactionStatsFilter) (interface{}, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repo.TransactionStatsFilter) interface{}); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repo.TransactionStatsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserStorer) GetUserByEmail(ctx context.Context, email string) (repo.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repo.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repo.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserHighestRole provides a mock function with given fields: ctx, userID
func (_m *UserStorer) GetUserHighestRole(ctx context.Context, userID string) (int, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserHighestRole")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserInfo provides a mock function with given fields: ctx, userID
func (_m *UserStorer) GetUserInfo(ctx context.Context, userID string) (utils.UserInfo, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 utils.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (utils.UserInfo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) utils.UserInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(utils.UserInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetuserByID provides a mock function with given fields: ctx, userID
func (_m *UserStorer) GetuserByID(ctx context.Context, userID string) (repo.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetuserByID")
	}

	var r0 repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (repo.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) repo.User); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(repo.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertKYCVerification provides a mock function with given fields: ctx, userID, documentType, documentNumber, verificationStatus
func (_m *UserStorer) InsertKYCVerification(ctx context.Context, userID string, documentType string, documentNumber string, verificationStatus string) (string, error) {
	ret := _m.Called(ctx, userID, documentType, documentNumber, verificationStatus)

	if len(ret) == 0 {
		panic("no return value specified for InsertKYCVerification")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (string, error)); ok {
		return rf(ctx, userID, documentType, documentNumber, verificationStatus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) string); ok {
		r0 = rf(ctx, userID, documentType, documentNumber, verificationStatus)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, userID, documentType, documentNumber, verificationStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKYCVerificationStatus provides a mock function with given fields: ctx, user_id, verificationStatus, verifiedBy
func (_m *UserStorer) UpdateKYCVerificationStatus(ctx context.Context, user_id string, verificationStatus string, verifiedBy string) error {
	ret := _m.Called(ctx, user_id, verificationStatus, verifiedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateKYCVerificationStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, user_id, verificationStatus, verifiedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLastLogin provides a mock function with given fields: ctx, userID
func (_m *UserStorer) UpdateLastLogin(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRequestLog provides a mock function with given fields: ctx, requestID, responseStatus, responseTimeMs
func (_m *UserStorer) UpdateRequestLog(ctx context.Context, requestID string, responseStatus int, responseTimeMs int) error {
	ret := _m.Called(ctx, requestID, responseStatus, responseTimeMs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRequestLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) error); ok {
		r0 = rf(ctx, requestID, responseStatus, responseTimeMs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserPasswordHash provides a mock function with given fields: ctx, userID, newPasswordHash
func (_m *UserStorer) UpdateUserPasswordHash(ctx context.Context, userID string, newPasswordHash string) error {
	ret := _m.Called(ctx, userID, newPasswordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPasswordHash")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, newPasswordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserExists provides a mock function with given fields: ctx, userName, email
func (_m *UserStorer) UserExists(ctx context.Context, userName string, email string) (bool, bool, error) {
	ret := _m.Called(ctx, userName, email)

	if len(ret) == 0 {
		panic("no return value specified for UserExists")
	}

	var r0 bool
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, bool, error)); ok {
		return rf(ctx, userName, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userName, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, userName, email)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, userName, email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewUserStorer creates a new instance of UserStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStorer {
	mock := &UserStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
