// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	mock "github.com/stretchr/testify/mock"

	repo "github.com/CodeWithKrushnal/ChainBank/internal/repo"

	time "time"

	uuid "github.com/google/uuid"
)

// WalletStorer is an autogenerated mock type for the WalletStorer type
type WalletStorer struct {
	mock.Mock
}

// AddTransaction provides a mock function with given fields: ctx, transactionID, senderWalletID, receiverWalletID, amount, transactionType, status, transactionHash, fee
func (_m *WalletStorer) AddTransaction(ctx context.Context, transactionID uuid.UUID, senderWalletID string, receiverWalletID string, amount *big.Float, transactionType string, status string, transactionHash string, fee *big.Float) (repo.Transaction, error) {
	ret := _m.Called(ctx, transactionID, senderWalletID, receiverWalletID, amount, transactionType, status, transactionHash, fee)

	if len(ret) == 0 {
		panic("no return value specified for AddTransaction")
	}

	var r0 repo.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, *big.Float, string, string, string, *big.Float) (repo.Transaction, error)); ok {
		return rf(ctx, transactionID, senderWalletID, receiverWalletID, amount, transactionType, status, transactionHash, fee)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, *big.Float, string, string, string, *big.Float) repo.Transaction); ok {
		r0 = rf(ctx, transactionID, senderWalletID, receiverWalletID, amount, transactionType, status, transactionHash, fee)
	} else {
		r0 = ret.Get(0).(repo.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, *big.Float, string, string, string, *big.Float) error); ok {
		r1 = rf(ctx, transactionID, senderWalletID, receiverWalletID, amount, transactionType, status, transactionHash, fee)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionByID provides a mock function with given fields: ctx, transactionID
func (_m *WalletStorer) GetTransactionByID(ctx context.Context, transactionID uuid.UUID) (repo.Transaction, error) {
	ret := _m.Called(ctx, transactionID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionByID")
	}

	var r0 repo.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (repo.Transaction, error)); ok {
		return rf(ctx, transactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) repo.Transaction); ok {
		r0 = rf(ctx, transactionID)
	} else {
		r0 = ret.Get(0).(repo.Transaction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, transactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactions provides a mock function with given fields: ctx, transactionID, senderWalletID, receiverWalletID, commonWalletID, fromTime, toTime, page, limit
func (_m *WalletStorer) GetTransactions(ctx context.Context, transactionID uuid.UUID, senderWalletID string, receiverWalletID string, commonWalletID string, fromTime time.Time, toTime time.Time, page int, limit int) ([]repo.Transaction, error) {
	ret := _m.Called(ctx, transactionID, senderWalletID, receiverWalletID, commonWalletID, fromTime, toTime, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactions")
	}

	var r0 []repo.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, time.Time, time.Time, int, int) ([]repo.Transaction, error)); ok {
		return rf(ctx, transactionID, senderWalletID, receiverWalletID, commonWalletID, fromTime, toTime, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, time.Time, time.Time, int, int) []repo.Transaction); ok {
		r0 = rf(ctx, transactionID, senderWalletID, receiverWalletID, commonWalletID, fromTime, toTime, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repo.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string, time.Time, time.Time, int, int) error); ok {
		r1 = rf(ctx, transactionID, senderWalletID, receiverWalletID, commonWalletID, fromTime, toTime, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWalletID provides a mock function with given fields: ctx, email, userID
func (_m *WalletStorer) GetWalletID(ctx context.Context, email string, userID string) (string, error) {
	ret := _m.Called(ctx, email, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, email, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertPrivateKey provides a mock function with given fields: ctx, userID, walletID, privateKey
func (_m *WalletStorer) InsertPrivateKey(ctx context.Context, userID string, walletID string, privateKey string) error {
	ret := _m.Called(ctx, userID, walletID, privateKey)

	if len(ret) == 0 {
		panic("no return value specified for InsertPrivateKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, walletID, privateKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrievePrivateKey provides a mock function with given fields: ctx, userID, walletID
func (_m *WalletStorer) RetrievePrivateKey(ctx context.Context, userID string, walletID string) (string, error) {
	ret := _m.Called(ctx, userID, walletID)

	if len(ret) == 0 {
		panic("no return value specified for RetrievePrivateKey")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, userID, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, userID, walletID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBalance provides a mock function with given fields: ctx, walletID, balance
func (_m *WalletStorer) UpdateBalance(ctx context.Context, walletID string, balance *big.Float) error {
	ret := _m.Called(ctx, walletID, balance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *big.Float) error); ok {
		r0 = rf(ctx, walletID, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateWalletBalance provides a mock function with given fields: ctx, userID, balance
func (_m *WalletStorer) UpdateWalletBalance(ctx context.Context, userID string, balance *big.Float) error {
	ret := _m.Called(ctx, userID, balance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWalletBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *big.Float) error); ok {
		r0 = rf(ctx, userID, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletStorer creates a new instance of WalletStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletStorer {
	mock := &WalletStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
