// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	ecdsa "crypto/ecdsa"
	big "math/big"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// EthRepo is an autogenerated mock type for the EthRepo type
type EthRepo struct {
	mock.Mock
}

// CreateWallet provides a mock function with given fields: password
func (_m *EthRepo) CreateWallet(password string) (string, *ecdsa.PrivateKey, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 string
	var r1 *ecdsa.PrivateKey
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, *ecdsa.PrivateKey, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) *ecdsa.PrivateKey); ok {
		r1 = rf(password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ecdsa.PrivateKey)
		}
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PreloadTokens provides a mock function with given fields: walletAddress, amount
func (_m *EthRepo) PreloadTokens(walletAddress string, amount *big.Int) error {
	ret := _m.Called(walletAddress, amount)

	if len(ret) == 0 {
		panic("no return value specified for PreloadTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *big.Int) error); ok {
		r0 = rf(walletAddress, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferFunds provides a mock function with given fields: fromPrivateKeyHex, fromAddressHex, toAddressHex, amount, gasPrice, gasLimit, chainID
func (_m *EthRepo) TransferFunds(fromPrivateKeyHex string, fromAddressHex string, toAddressHex string, amount *big.Int, gasPrice *big.Int, gasLimit uint64, chainID *big.Int) (*types.Transaction, error) {
	ret := _m.Called(fromPrivateKeyHex, fromAddressHex, toAddressHex, amount, gasPrice, gasLimit, chainID)

	if len(ret) == 0 {
		panic("no return value specified for TransferFunds")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, *big.Int, *big.Int, uint64, *big.Int) (*types.Transaction, error)); ok {
		return rf(fromPrivateKeyHex, fromAddressHex, toAddressHex, amount, gasPrice, gasLimit, chainID)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, *big.Int, *big.Int, uint64, *big.Int) *types.Transaction); ok {
		r0 = rf(fromPrivateKeyHex, fromAddressHex, toAddressHex, amount, gasPrice, gasLimit, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, *big.Int, *big.Int, uint64, *big.Int) error); ok {
		r1 = rf(fromPrivateKeyHex, fromAddressHex, toAddressHex, amount, gasPrice, gasLimit, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEthRepo creates a new instance of EthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *EthRepo {
	mock := &EthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
